version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 16.15.1
    - 16.16.0
    - 17.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.5.0
  - dependency-name: next-pwa
    versions:
    - 5.5.4
  - dependency-name: eslint
    versions:
    - 8.18.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.5.9
  - dependency-name: "@storybook/react"
    versions:
    - 6.5.9
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.16.4
  - dependency-name: "@babel/core"
    versions:
    - 7.18.6
  - dependency-name: jest-styled-components
    versions:
    - 7.0.8
  - dependency-name: eslint-plugin-prettier
    versions:
    - 4.2.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 5.30.3
  - dependency-name: styled-components
    versions:
    - 5.3.5
  - dependency-name: next
    versions:
    - 12.2.0
  - dependency-name: husky
    versions:
    - 8.0.0
  - dependency-name: "@types/jest"
    versions:
    - 28.1.4
  - dependency-name: eslint-plugin-react
    versions:
    - 7.30.1
  - dependency-name: react-dom
    versions:
    - 18.2.0
  - dependency-name: react
    versions:
    - 18.2.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 5.30.3
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.25
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.7.4
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.18.6
  - dependency-name: "@testing-library/react"
    versions:
    - 13.3.0